

name: Review changes on Dev (Commits/PRs)

on:
  push:
    branches: ['dev']
  pull_request:
    types:
      - opened

jobs:
  code-check:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: run unit tests and coverage scan
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          RAVE_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: mvn test

      - name: upload coverage report to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: push build status to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()